name: Build Go Linux binaries
on:
  workflow_call:
    inputs:
      output:
        type: string
        description: Binary output name
        required: true
      tags:
        type: string
        description: Build tags
      prebuild:
        type: string
        description: Command to run before building

jobs:
  build-linux_386:
    uses: ./.github/workflows/go-builder.yaml
    with:
      goos: linux
      goarch: 386
      archid: linux_x86
      output: ${{inputs.output}}
      tags: ${{inputs.tags}}
      prebuild: ${{inputs.prebuild}}
  build-linux_arm:
    uses: ./.github/workflows/go-builder.yaml
    with:
      goos: linux
      goarch: arm
      archid: linux_arm
      output: ${{inputs.output}}
      tags: ${{inputs.tags}}
      prebuild: ${{inputs.prebuild}}
