name: Build Go binary
on:
  workflow_call:
    inputs:
      goos:
        type: string
        description: GOOS
        required: true
      goarch:
        type: string
        description: GOARCH
        required: true
      archid:
        type: string
        description: Arch ID
        required: true
      output:
        type: string
        description: Binary output name
        required: true
      tags:
        type: string
        description: Build tags
      prebuild:
        type: string
        description: Command to run before building

jobs:
  build:
    name: build-${{inputs.archid}}
    runs-on: ubuntu-22.04
    env:
      ARCHID: ${{inputs.archid}}
      TAGS: ${{inputs.tags}}
      OUT: ${{inputs.output}}
      ARCHIVE: ${{inputs.output}}-${{inputs.archid}}.tar.gz
    steps:
      - name: Setup source repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19.3"
      - name: Run prebuild command
        run: ${{inputs.prebuild}}
      - name: Build binary
        env:
          GOOS: ${{inputs.goos}}
          GOARCH: ${{inputs.goarch}}
        run: go build -tags "$TAGS" -o "out/bin/$OUT" .
      - name: Copy license file
        run: cp LICENSE out/
      - name: Create archive
        run: |
          cd out && \
          tar -zcvf "../$ARCHIVE" . && \
          cd ..
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.ARCHIVE}}
          path: ${{env.ARCHIVE}}
